name: api-data 
on:
  push:
    branches: [ master ]  
  schedule:
    - cron: "*/5 * * * *"
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - name: wget 
      run: |
        wget -O recent.json ${{ secrets.API_RECENT }} 
        wget -O popular.json ${{ secrets.API_POPULAR }} 
        wget -O view.json ${{ secrets.API_VIEW }} 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./